//Auto-generated by makefile

#ifndef __PROJINFO_H__
#define __PROJINFO_H__
#include <inttypes.h>

#if (!defined(PROJINFO_SHORT) || !PROJINFO_SHORT)
 uint8_t __attribute__ ((progmem)) \
   header0[] = " /Users/meh/_avrProjects/tabletBluetoother/8-gittifying ";
 uint8_t __attribute__ ((progmem)) \
   header1[] = " Mon Dec 23 08:00:44 PST 2013 ";
 uint8_t __attribute__ ((progmem)) \
   headerOpt[] = " WDT_DIS=TRUE ";
#else //projInfo Shortened
 uint8_t __attribute__ ((progmem)) \
   header[] = "tabletBluetoother8 2013-12-23 08:00:44";
#endif

//For internal use...
//Currently only usable in main.c
#define PROJ_VER 8
#define COMPILE_YEAR 2013

#endif

